version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ubuntu/build/

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu

hooks:
  BeforeInstall:
    - location: deploy-before.sh
      runas: ubuntu
      
  ApplicationStart:
    - location: deploy.sh
      runas: ubuntu
